<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-0KDP1L5" name="com.clc.java.collection.TestLoginFunctionality" tests="5" failures="1" timestamp="2 Apr 2019 10:43:12 GMT" time="0.034" errors="0">
  <testcase name="verifyInvalidCredentionals" time="0.006" classname="com.clc.java.collection.TestLoginFunctionality">
    <failure type="java.lang.AssertionError" message="expected [Username cannot be Empty] but found [Password cannot be Empty]">
      <![CDATA[java.lang.AssertionError: expected [Username cannot be Empty] but found [Password cannot be Empty]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.clc.java.collection.TestLoginFunctionality.verifyInvalidCredentionals(TestLoginFunctionality.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- verifyInvalidCredentionals -->
  <testcase name="verifyInvalidCredentionals" time="0.011" classname="com.clc.java.collection.TestLoginFunctionality"/>
  <testcase name="verifyInvalidCredentionals" time="0.002" classname="com.clc.java.collection.TestLoginFunctionality"/>
  <testcase name="verifyInvalidCredentionals" time="0.002" classname="com.clc.java.collection.TestLoginFunctionality"/>
  <testcase name="verifyInvalidCredentionals" time="0.013" classname="com.clc.java.collection.TestLoginFunctionality"/>
</testsuite> <!-- com.clc.java.collection.TestLoginFunctionality -->
